apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: toooghj
  description: provision webapp for dev environment
spec:
  owner: group:default/guests
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: toooghj
  description: provision webapp for dev environment
  annotations:
     backstage.io/techdocs-ref: dir:./docs
     github.com/project-slug: prayankag/toooghj/actions    
spec:
  type: service
  owner: group:default/guests
  lifecycle: experimental
  system: toooghj
  providesApis:
    - toooghj
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: toooghj
  description: provision webapp for dev environment
spec:
  type: internal
  lifecycle: experimental
  owner: group:default/guests
  system: toooghj
  definition: "provision webapp for dev environment"
